### ISSUE TITLE
Could not find a declaration file for module '@etchteam/next-pagination'.

### ISSUE THREAD

**Issue by vitorklock** [etchteam/next-pagination#45]
Found an error while trying to import Pagination from `'@etchteam/next-pagination'`. While importing `'@etchteam/next-pagination/dist/index.css'` works. Error goes as follows:
```
Could not find a declaration file for module '@etchteam/next-pagination'. '/home/myuser/Documents/VisualStudioProjects/myproject/node_modules/@etchteam/next-pagination/dist/index.js' implicitly has an 'any' type.
```
It appears the error is from typescript, I solved it by using `// @ts-expect-error` on the line above it, not the best of solutions.

**Comment by DanWebb** [comment]
Hey @vitorklock this has been fixed in v3.5.3 👍 

In case you run into this problem in the future on different projects, you could fix this yourself by either:

- Creating a [typescript declaration](https://www.typescriptlang.org/docs/handbook/declaration-files/by-example.html) file in your local project
- Submitting a PR to add typescript definitions to the project
- Adding to types for the project to https://github.com/DefinitelyTyped/DefinitelyTyped
