### ISSUE TITLE
Update to next 13

### ISSUE THREAD

**Issue by bartek2341** [etchteam/next-pagination#63]
Hi, somebody found a way to make this work with next 13?

**Comment by DanWebb** [comment]
This works with Next 13 out of the box.

The only issue discovered whilst testing is there's a double anchor output in the HTML:

![Screenshot 2023-03-02 at 08 26 44](https://user-images.githubusercontent.com/5038459/222374355-93e40c82-e628-48a3-8053-0b41f24e8120.png)

I'm guessing this will be because of the latest Link component changes and the `legacyBehaviour` prop needs to be passed at https://github.com/etchteam/next-pagination/blob/200c901f9083fbcc320a982c7fb908ac3f1045b2/src/index.tsx#L128

**Comment by osseonews** [comment]
Thanks for the great lib, and thanks for fixing the Link issue with Next 13, as we just ran into this.
